# Generated by Django 4.1.1 on 2022-10-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
